[package]
name = "wordle"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
debug = true

[dependencies]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "grade1"
harness = false
